### ISSUE TITLE
Readme.md Does Not Serve the Purpose It Should Serve

### ISSUE THREAD

**Issue by Spa-ce42** [kaylawang05/SeniorHomeApp#1]
Readme.md files should show contents that help the users to set up and use the projects, instead of content that is helpful to the developers, the developers use something called documentation to get involved in the project faster.

**Comment by Broyojo** [comment]
The new readme in v2 is better and should do what you suggest. You can take a look and give some more recommendations.

**Comment by Spa-ce42** [comment]
The information on what each file or method actually does could be put inside .py files as block comments.

**Comment by Broyojo** [comment]
it is done now
