### ISSUE TITLE
The folder v1 and v2 may be put in different branches.

### ISSUE THREAD

**Issue by Spa-ce42** [kaylawang05/SeniorHomeApp#5]
The current layout ignores the more powerful branching of repositories that Github provides. Read more at: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches.

**Comment by Broyojo** [comment]
So, do you suggest that we create a separate branch for v1 and make v2 the main branch? We are just keeping the v1 code for reference if we need to look at some old GUI code.

**Comment by Spa-ce42** [comment]
Yes.

**Comment by Divak2004** [comment]
@Spa-ce42 could we know who you are in the discord?

**Comment by Spa-ce42** [comment]
I wasn't introduced to a discord server, but I did sign up for this through this Gmail address: kfei0921@gmail.com.

**Comment by Divak2004** [comment]
Ah cool. Here’s the discord link: https://discord.gg/kbYpAhba <https://discord.gg/kbYpAhba>

Sincerely,
David

**Comment by Broyojo** [comment]
it is done now
